version: '3.8'

services:
  conversao-temperatura:
    container_name: app
    image: ivanjuniordocker/conversao-temperatura:${TAG}
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080